<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Aryasindhus-MacBook-Air.local" name="Command line test 8ca6219f-6983-4827-80e0-1af03ba988a9" tests="3" failures="1" timestamp="16 Nov 2016 16:27:23 GMT" time="0.032" errors="0">
  <testcase name="add" time="0.005" classname="com.test.calculator.CalcTest"/>
  <testcase name="add" time="0.0" classname="com.test.calculator.CalcTest"/>
  <testcase name="add" time="0.001" classname="com.test.calculator.CalcTest">
    <failure type="java.lang.AssertionError" message="Addition is Wrong expected [44] but found [33]">
      <![CDATA[java.lang.AssertionError: Addition is Wrong expected [44] but found [33]
	at com.test.calculator.CalcTest.add(CalcTest.java:14)
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:116)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:745)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- add -->
</testsuite> <!-- Command line test 8ca6219f-6983-4827-80e0-1af03ba988a9 -->
